#!/usr/bin/env python3
"""Extract a single version's entry from CHANGELOG.md for use as release
notes (GitHub Release body and docs-website PR body).

CHANGELOG.md is generated by semantic-release using this repo's
.releaserc.json, which already writes section headers in the standard
format (### New features / ### Improvements / ### Bug fixes) — this script
does not rename anything, it only extracts the right version's block and
strips the trailing commit-hash link from each bullet.

Usage:
    extract-changelog-notes.py <path-to-CHANGELOG.md> <version>

Prints the notes to stdout. Never fails the pipeline: if the version isn't
found or its block has no content, prints a fallback line and exits 0.
"""
import re
import sys

# Stop at the next version heading ("## [x.y.z]...") or at any top-level H1
# ("# ...") — the latter guards against stray legacy boilerplate (e.g. an old
# "# Changelog" title left sitting between historical entries) that would
# otherwise get swept into the extracted block.
HEADING_RE = re.compile(r"^##\s+\[|^#\s")
COMMIT_LINK_RE = re.compile(r"\s*\(\[[0-9a-f]{6,40}\]\([^)]*\)\)\s*$")
FALLBACK = "_No new features, improvements, or bug fixes for this release._\n"


def extract_version_block(changelog_text, version):
    lines = changelog_text.splitlines()
    version_heading_re = re.compile(r"^##\s+\[" + re.escape(version) + r"\]")

    start = None
    for i, line in enumerate(lines):
        if version_heading_re.match(line):
            start = i + 1
            break
    if start is None:
        return []

    end = len(lines)
    for j in range(start, len(lines)):
        if HEADING_RE.match(lines[j]):
            end = j
            break
    return lines[start:end]


def clean(block_lines):
    cleaned = [COMMIT_LINK_RE.sub("", line) for line in block_lines]
    text = "\n".join(cleaned).strip("\n")
    return text


def main():
    if len(sys.argv) != 3:
        raise SystemExit(f"Usage: {sys.argv[0]} <CHANGELOG.md path> <version>")
    changelog_path, version = sys.argv[1], sys.argv[2]

    with open(changelog_path, encoding="utf-8") as f:
        text = f.read()

    block = extract_version_block(text, version)
    cleaned = clean(block)

    if not cleaned:
        sys.stdout.write(FALLBACK)
        return

    sys.stdout.write(cleaned + "\n")


if __name__ == "__main__":
    main()
